language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '5.8'
  - '4.0'
env:
  - DB=mysql
  
services:
  - docker
  
before_script:
  - docker pull gizra/drupal-lamp

script:
  - docker run -it -p 8080:80 gizra/drupal-lamp
